# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(loginid:"admin", password:"pass")

# 宗派一覧
Sect.create(sect:"浄土真宗 東")
Sect.create(sect:"浄土真宗 西")
Sect.create(sect:"浄土宗")
Sect.create(sect:"曹洞宗")
Sect.create(sect:"臨済宗")
Sect.create(sect:"天台宗")
Sect.create(sect:"日蓮宗")
Sect.create(sect:"真言宗")
Sect.create(sect:"神徒")
Sect.create(sect:"キリスト教")
Sect.create(sect:"日蓮正宗")
Sect.create(sect:"世界救世教")
Sect.create(sect:"その他・不明")
Sect.create(sect:"新 世界救世教")
Sect.create(sect:"天理教")
Sect.create(sect:"大本教")
Sect.create(sect:"学会")
Sect.create(sect:"浄土真宗（西・東不明）")
Sect.create(sect:"無宗教")
Sect.create(sect:"真宗（西・東以外）")
Sect.create(sect:"法華宗")

# 会種一覧
Kind.find_or_create_by(id:1, text: "全道庁ＯＢ")
Kind.find_or_create_by(id:2, text: "道友会")
Kind.find_or_create_by(id:3, text: "道現職")
Kind.find_or_create_by(id:4, text: "北退教")
Kind.find_or_create_by(id:5, text: "現公立教職")
Kind.find_or_create_by(id:6, text: "炭鉱離職者")
Kind.find_or_create_by(id:7, text: "開発局ＯＢ")
Kind.find_or_create_by(id:8, text: "鉄道ＯＢ")
Kind.find_or_create_by(id:9, text: "教育互助センター扱い")
Kind.find_or_create_by(id:11, text: "全道庁ＯＢ名簿なし")
Kind.find_or_create_by(id:19, text: "共済会分・民間")
Kind.find_or_create_by(id:20, text: "札退連西区支部")
Kind.find_or_create_by(id:21, text: "郵政退職者会")
Kind.find_or_create_by(id:22, text: "ＮＴＴ労組")
Kind.find_or_create_by(id:30, text: "ハマナス会在宅")
Kind.find_or_create_by(id:40, text: "道組合")
Kind.find_or_create_by(id:41, text: "北広島職労")
Kind.find_or_create_by(id:42, text: "道ＯＢ空知")
Kind.find_or_create_by(id:43, text: "農林省 退職者の会")
Kind.find_or_create_by(id:49, text: "ハ施工後入会")
Kind.find_or_create_by(id:50, text: "道ＯＢ名なし家族")
Kind.find_or_create_by(id:51, text: "※道ＯＢ家族会員")
Kind.find_or_create_by(id:52, text: "※道友会家族会員")
Kind.find_or_create_by(id:53, text: "※道現職家族会員")
Kind.find_or_create_by(id:54, text: "※北退教家族会員")
Kind.find_or_create_by(id:55, text: "※公立現家族会員")
Kind.find_or_create_by(id:56, text: "※炭労家族会員")
Kind.find_or_create_by(id:57, text: "※開発局ＯＢ家族会員")
Kind.find_or_create_by(id:58, text: "※鉄道ＯＢ家族会員")
Kind.find_or_create_by(id:59, text: "※互助セ家族会員")
Kind.find_or_create_by(id:60, text: "※ＮＳ2000家族会員")
Kind.find_or_create_by(id:61, text: "※日蓮正宗家族会員")
Kind.find_or_create_by(id:62, text: "※㈱ホクシン家族会員")
Kind.find_or_create_by(id:63, text: "※その他扱い家族会員")
Kind.find_or_create_by(id:64, text: "風羅家族会員")
Kind.find_or_create_by(id:600, text: "※ＮＳ2000")
Kind.find_or_create_by(id:700, text: "※日蓮正宗お葬儀の会")
Kind.find_or_create_by(id:710, text: "悠友の会")
Kind.find_or_create_by(id:720, text: "蓮の会（北税協）")
Kind.find_or_create_by(id:730, text: "Dearness")
Kind.find_or_create_by(id:731, text: "ディアネスエリア")
Kind.find_or_create_by(id:732, text: "老人施設")
Kind.find_or_create_by(id:733, text: "郵便局")
Kind.find_or_create_by(id:739, text: "郵×エリア")
Kind.find_or_create_by(id:740, text: "企業 Dearness")
Kind.find_or_create_by(id:750, text: "糧友会")
Kind.find_or_create_by(id:800, text: "㈱ホクシン")
Kind.find_or_create_by(id:900, text: "その他扱い")
Kind.find_or_create_by(id:1000, text: "ＣＢ風羅")
Kind.find_or_create_by(id:1100, text: "日専連ﾗｲﾌｸﾗﾌﾞ")
Kind.find_or_create_by(id:1101, text: "日専連社員")
Kind.find_or_create_by(id:1200, text: "ニ/Dearness")
Kind.find_or_create_by(id:2000, text: "※道ＯＢ未加入")
Kind.find_or_create_by(id:2005, text: "道ＯＢ空知未加入")
Kind.find_or_create_by(id:2006, text: "道ＯＢ後志未加入")
Kind.find_or_create_by(id:2010, text: "※道友会未加入")
Kind.find_or_create_by(id:2040, text: "※北退教未加入")
Kind.find_or_create_by(id:2060, text: "※炭労未加入")
Kind.find_or_create_by(id:2080, text: "※鉄道未加入")
Kind.find_or_create_by(id:2090, text: "道組合未加入")
Kind.find_or_create_by(id:2100, text: "開発局未加入")
Kind.find_or_create_by(id:2110, text: "全農林未加入")
Kind.find_or_create_by(id:2120, text: "糧友会 未加入")
Kind.find_or_create_by(id:3000, text: "正宗未加入")
Kind.find_or_create_by(id:3010, text: "蓮の会（北税協）未加入")
Kind.find_or_create_by(id:5000, text: "名変ﾊﾏﾅｽ家族会員")
Kind.find_or_create_by(id:5010, text: "名変風羅家族会員")
Kind.find_or_create_by(id:8000, text: "PG用名簿")
Kind.find_or_create_by(id:9000, text: "エリア未加入")
Kind.find_or_create_by(id:9990, text: "退会希望")
Kind.find_or_create_by(id:9991, text: "お亡くなり")
Kind.find_or_create_by(id:9992, text: "住所不明")
Kind.find_or_create_by(id:9998, text: "風羅送付不可者")
Kind.find_or_create_by(id:9999, text: "送付不可者")

# 式場一覧
Ceremonialplace.find_or_create_by(id:1,name: "札幌斎場", address: "札幌市豊平区平岸4-15",tel: "0118210631")
Ceremonialplace.find_or_create_by(id:2,name: "北海斎場", address: "札幌市豊平区豊平4-3",tel: "0118244444")
Ceremonialplace.find_or_create_by(id:3,name: "麻生斎場", address: "札幌市北区北4０条西6",tel: "0117074444")
Ceremonialplace.find_or_create_by(id:4,name: "てんぱん斎場", address: "札幌市東区北51東2",tel: "0117121000")
Ceremonialplace.find_or_create_by(id:5,name: "セレモニーホール青柳", address: "札幌市東区北19東22",tel: "0117847300")
Ceremonialplace.find_or_create_by(id:6,name: "むすめや西区斎場", address: "札幌市西区西町北8",tel: "0116611144")
Ceremonialplace.find_or_create_by(id:7,name: "北広島斎場", address: "北広島市中央2-4",tel: "3734444")
Ceremonialplace.find_or_create_by(id:8,name: "東北野会館", address: "札幌市清田区北野4条5丁目4-55",tel: "0118811449")
Ceremonialplace.find_or_create_by(id:9,name: "大宥寺仏教会館", address: "札幌市中央区南11条西13丁目",tel: "0115515511")
Ceremonialplace.find_or_create_by(id:10,name: "瑞龍寺花園会館", address: "札幌市中央区南2条西20丁目",tel: "0116113228")
Ceremonialplace.find_or_create_by(id:11,name: "中ノ沢会館", address: "札幌市南区中ノ沢",tel: "")
Ceremonialplace.find_or_create_by(id:12,name: "南沢福祉会館", address: "札幌市南区南沢",tel: "")
Ceremonialplace.find_or_create_by(id:13,name: "西野第一会館", address: "札幌市西区西野6-8-10-33",tel: "0116634224")
Ceremonialplace.find_or_create_by(id:14,name: "玉宝禅寺", address: "札幌市清田区北野7-2",tel: "0118837676")
Ceremonialplace.find_or_create_by(id:15,name: "新川記念会館", address: "札幌市北区新川3条18丁目2-1",tel: "0117653612")
Ceremonialplace.find_or_create_by(id:16,name: "新善光寺", address: "札幌市中央区南6条西1丁目",tel: "0115110262")
Ceremonialplace.find_or_create_by(id:17,name: "夢トピアコスモプラザ", address: "札幌市手稲区星置1条1丁目",tel: "0116843588")
Ceremonialplace.find_or_create_by(id:18,name: "カトリック円山教会", address: "札幌市中央区",tel: "0116314215")
Ceremonialplace.find_or_create_by(id:19,name: "前田四季彩の街会館", address: "札幌市手稲区前田8条15丁目15-1",tel: "0116844580")
Ceremonialplace.find_or_create_by(id:20,name: "清田会館", address: "札幌市清田区平岡2条1丁目",tel: "0118812445")
Ceremonialplace.find_or_create_by(id:21,name: "西本願寺札幌別院", address: "札幌市中央区北3条西19丁目",tel: "0116119322")
Ceremonialplace.find_or_create_by(id:22,name: "山の手会館", address: "札幌市西区山の手３条２丁目",tel: "0116423866")
Ceremonialplace.find_or_create_by(id:23,name: "はなみつ斎場", address: "札幌市東区北28条東8丁目",tel: "0117424949")
Ceremonialplace.find_or_create_by(id:24,name: "大行寺興正閣", address: "札幌市厚別区厚別中央3-5",tel: "0118912005")
Ceremonialplace.find_or_create_by(id:25,name: "札幌御苑", address: "札幌市白石区本通13丁目南9‐8",tel: "0118652695")
Ceremonialplace.find_or_create_by(id:26,name: "手稲北海斎場", address: "札幌市手稲区富丘2条5丁目",tel: "0116834444")
Ceremonialplace.find_or_create_by(id:27,name: "てんぱん手稲斎場", address: "札幌市手稲区本町2丁目",tel: "0116829494")
Ceremonialplace.find_or_create_by(id:28,name: "セレモニーパレス手稲", address: "札幌市手稲区前田4条8丁目",tel: "0116844444")
Ceremonialplace.find_or_create_by(id:29,name: "白石記念斎場", address: "札幌市白石区本通4丁目",tel: "0118664444")
Ceremonialplace.find_or_create_by(id:30,name: "むすめや厚別斎場", address: "札幌市厚別区厚別中央1条2丁目",tel: "0118911155")
Ceremonialplace.find_or_create_by(id:31,name: "むすめや市民斎場", address: "札幌市豊平区平岸5条13丁目",tel: "0118242141")
Ceremonialplace.find_or_create_by(id:32,name: "浄願寺ホール（中の島ホール）", address: "札幌市豊平区中の島1条2丁目",tel: "0118410983")
Ceremonialplace.find_or_create_by(id:33,name: "美園斎場", address: "札幌市豊平区美園3条2丁目",tel: "0118424444")
Ceremonialplace.find_or_create_by(id:34,name: "清田斎場", address: "札幌市清田区清田1条1丁目",tel: "0118814444")
Ceremonialplace.find_or_create_by(id:35,name: "慶兆苑斎場", address: "江別市一番町4‐4",tel: "3814444")
Ceremonialplace.find_or_create_by(id:36,name: "むすめや大麻市民斎場", address: "江別市大麻中町26‐10",tel: "3871144")
Ceremonialplace.find_or_create_by(id:37,name: "札幌霊堂", address: "札幌市豊平区平岸4‐15",tel: "0118218086")
Ceremonialplace.find_or_create_by(id:38,name: "札苗会館", address: "札幌市東区",tel: "")
Ceremonialplace.find_or_create_by(id:39,name: "大導寺会館", address: "札幌市東区苗穂町２丁目2-3",tel: "0117427703")
Ceremonialplace.find_or_create_by(id:40,name: "伏古記念会館", address: "札幌市東区",tel: "")
Ceremonialplace.find_or_create_by(id:41,name: "ディアネス札幌", address: "札幌市西区八軒10条西12丁目6-3",tel: "")
Ceremonialplace.find_or_create_by(id:45,name: "ディアネス屯田", address: "札幌市北区屯田9条2丁目8-8",tel: "")
Ceremonialplace.find_or_create_by(id:48,name: "札幌斎場", address: "札幌市豊平区平岸4条15丁目3-19",tel: "0118210631")
Ceremonialplace.find_or_create_by(id:49,name: "メモリアホール厚別", address: "札幌市厚別区上野幌1条3丁目1-5",tel: "0118966452")
Ceremonialplace.find_or_create_by(id:50,name: "メモリアホール江別中央", address: "江別市中央町29番地10号",tel: "0113814441")
Ceremonialplace.find_or_create_by(id:51,name: "白石中央斎場", address: "白石区中央2条3丁目4-10", tel: "0118208101")
# 担当者一覧
Employee.create(name:"志田 宗夫")
Employee.create(name:"横内 直樹")
Employee.create(name:"岡田 英憲")
Employee.create(name:"志田 優子")
Employee.create(name:"新田 美由紀")
Employee.create(name:"増子 美津子")
Employee.create(name:"本間 秀隆")
Employee.create(name:"菊地 浩之")
Employee.create(name:"植木 弘子")
Employee.create(name:"荒 博愛")
Employee.create(name:"西田 義成")
Employee.create(name:"布施 秀樹")
Employee.create(name:"酒井 信明")
Employee.create(name:"佐藤 久代")
Employee.create(name:"木下 大作")
Employee.create(name:"平田 忠助")
Employee.create(name:"森 裕幸")
Employee.create(name:"和田 大")
Employee.create(name:"児玉 かおり")
Employee.create(name:"一條 稔員")
Employee.create(name:"宮腰 和")
Employee.create(name:"八谷 英生")
Employee.create(name:"永井 洋子")
Employee.create(name:"吉井 大")


Supplier.find_or_create_by(id:	0	,name: "斎場",tax: 	5	)
Supplier.find_or_create_by(id:	1	,name: "さっぽろセレモニー",tax: 	1	)
Supplier.find_or_create_by(id:	2	,name: "静岡園 2014",tax: 	1	)
Supplier.find_or_create_by(id:	3	,name: "ＮＫ北海道",tax: 	1	)
Supplier.find_or_create_by(id:	4	,name: "花粧",tax: 	1	)
Supplier.find_or_create_by(id:	5	,name: "花蓮",tax: 	1	)
Supplier.find_or_create_by(id:	6	,name: "14/3までの静岡園",tax: 	1	)
Supplier.find_or_create_by(id:	7	,name: "リバスタＰＦ",tax: 	1	)
Supplier.find_or_create_by(id:	8	,name: "北海道共済会",tax: 	1	)
Supplier.find_or_create_by(id:	9	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	10	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	11	,name: "北洋食品	",tax: 	1	)
Supplier.find_or_create_by(id:	15	,name: "北都ベリアール	",tax: 	4	)
Supplier.find_or_create_by(id:	16	,name: "",tax: 	7	)
Supplier.find_or_create_by(id:	17	,name: "徳礼	",tax: 	1	)
Supplier.find_or_create_by(id:	18	,name: "㈱木村	",tax: 	1	)
Supplier.find_or_create_by(id:	19	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	20	,name: "(有)クリエイティヴフォー	",tax: 	1	)
Supplier.find_or_create_by(id:	21	,name: "イオンライフ	",tax: 	4	)
Supplier.find_or_create_by(id:	22	,name: "国際経営（イオン）	",tax: 	1	)
Supplier.find_or_create_by(id:	23	,name: "北海道教育互助センター	",tax: 	7	)
Supplier.find_or_create_by(id:	24	,name: "日専連	",tax: 	7	)
Supplier.find_or_create_by(id:	25	,name: "北税協	",tax: 	7	)
Supplier.find_or_create_by(id:	26	,name: "グリーンアップル	",tax: 	7	)
Supplier.find_or_create_by(id:	27	,name: "いなづみ病院	",tax: 	7	)
Supplier.find_or_create_by(id:	28	,name: "いなづみ病院TMS	",tax: 	7	)
Supplier.find_or_create_by(id:	29	,name: "セディナ（ローン）	",tax: 	7	)
Supplier.find_or_create_by(id:	30	,name: "マコセ	",tax: 	1	)
Supplier.find_or_create_by(id:	31	,name: "ずずや	",tax: 	1	)
Supplier.find_or_create_by(id:	32	,name: "こもりコーポレーション	",tax: 	1	)
Supplier.find_or_create_by(id:	33	,name: "ユニクエストオンライン	",tax: 	4	)
Supplier.find_or_create_by(id:	34	,name: "鎌倉新書	",tax: 	4	)
Supplier.find_or_create_by(id:	35	,name: "業務提携先手数料	",tax: 	1	)
Supplier.find_or_create_by(id:	36	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	37	,name: "アウトソース	",tax: 	1	)
Supplier.find_or_create_by(id:	38	,name: "正栄企画	",tax: 	1	)
Supplier.find_or_create_by(id:	39	,name: "大栄繊維	",tax: 	1	)
Supplier.find_or_create_by(id:	40	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	41	,name: "イオンクレジット	",tax: 	7	)
Supplier.find_or_create_by(id:	42	,name: "カード会社	",tax: 	1	)
Supplier.find_or_create_by(id:	43	,name: "その他仕入先	",tax: 	1	)
Supplier.find_or_create_by(id:	44	,name: "マルゲン原	",tax: 	4	)
Supplier.find_or_create_by(id:	45	,name: "オリコローン	",tax: 	1	)
Supplier.find_or_create_by(id:	46	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	47	,name: "いなづみ24軒病院	",tax: 	7	)
Supplier.find_or_create_by(id:	48	,name: "",tax: 	7	)
Supplier.find_or_create_by(id:	49	,name: "その他の花屋	",tax: 	1	)
Supplier.find_or_create_by(id:	50	,name: "松岡満運輸など仏壇送料	",tax: 	1	)
Supplier.find_or_create_by(id:	51	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	52	,name: "",tax: 	7	)
Supplier.find_or_create_by(id:	53	,name: "天晴",tax: 	1	)
Supplier.find_or_create_by(id:	54	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	55	,name: "ディアネス貸館	",tax: 	1	)
Supplier.find_or_create_by(id:	60	,name: "北海道自動車	",tax: 	4	)
Supplier.find_or_create_by(id:	61	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	62	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	63	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	64	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	65	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	70	,name: "ジャパン唐和	",tax: 	1	)
Supplier.find_or_create_by(id:	71	,name: "ＪＣＢカード	",tax: 	7	)
Supplier.find_or_create_by(id:	72	,name: "ＶＩＳＡカード	",tax: 	7	)
Supplier.find_or_create_by(id:	73	,name: "イオンカード	",tax: 	7	)
Supplier.find_or_create_by(id:	74	,name: "Masterカード	",tax: 	7	)
Supplier.find_or_create_by(id:	75	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	76	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	77	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	78	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	79	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	80	,name: "法事部門・その他	",tax: 	1	)
Supplier.find_or_create_by(id:	81	,name: "法事部門・静岡園	",tax: 	1	)
Supplier.find_or_create_by(id:	82	,name: "法事部門・北洋食品	",tax: 	1	)
Supplier.find_or_create_by(id:	83	,name: "法事部門・花蓮	",tax: 	1	)
Supplier.find_or_create_by(id:	84	,name: "法事部門・さっぽろセレモニー	",tax: 	1	)
Supplier.find_or_create_by(id:	85	,name: "法事部門・北都ベリアール	",tax: 	1	)
Supplier.find_or_create_by(id:	86	,name: "法事部門・リバスタ･ピーエフ	",tax: 	1	)
Supplier.find_or_create_by(id:	87	,name: "法事部門・木村	",tax: 	1	)
Supplier.find_or_create_by(id:	88	,name: "法事部門・手数料売上	",tax: 	1	)
Supplier.find_or_create_by(id:	89	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	90	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	100	,name: "在庫商品	",tax: 	1	)
Supplier.find_or_create_by(id:	101	,name: "その他の役員代行	",tax: 	1	)
Supplier.find_or_create_by(id:	102	,name: "華サービス	",tax: 	1	)
Supplier.find_or_create_by(id:	103	,name: "献茶倶楽部	",tax: 	1	)
Supplier.find_or_create_by(id:	104	,name: "りあん	",tax: 	1	)
Supplier.find_or_create_by(id:	105	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	106	,name: "レガーロ・オフィス	",tax: 	1	)
Supplier.find_or_create_by(id:	107	,name: "詩音	",tax: 	1	)
Supplier.find_or_create_by(id:	108	,name: "若挟 千春	",tax: 	1	)
Supplier.find_or_create_by(id:	109	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	110	,name: "㈱北斗	",tax: 	1	)
Supplier.find_or_create_by(id:	111	,name: "北日本警備	",tax: 	1	)
Supplier.find_or_create_by(id:	1000	,name: "C4法事・さっぽろセレモニー	",tax: 	1	)
Supplier.find_or_create_by(id:	1001	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1002	,name: "C4法事・静岡園	",tax: 	1	)
Supplier.find_or_create_by(id:	1003	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1004	,name: "C4法事・テラキ生花店	",tax: 	1	)
Supplier.find_or_create_by(id:	1005	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1006	,name: "C4法事・花粧	",tax: 	1	)
Supplier.find_or_create_by(id:	1007	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1008	,name: "C4法事・北洋食品	",tax: 	1	)
Supplier.find_or_create_by(id:	1009	,name: "C4手数料売上	",tax: 	1	)
Supplier.find_or_create_by(id:	1010	,name: "C4法事・その他	",tax: 	1	)
Supplier.find_or_create_by(id:	1011	,name: "C4法事・訂正ホクシン	",tax: 	1	)
Supplier.find_or_create_by(id:	1012	,name: "C4法事・星川写真	",tax: 	1	)
Supplier.find_or_create_by(id:	1013	,name: "C4法事・マルゲン原	",tax: 	1	)
Supplier.find_or_create_by(id:	1014	,name: "C4法事・㈱木村	",tax: 	1	)
Supplier.find_or_create_by(id:	1015	,name: "C4法事・ずずや	",tax: 	1	)
Supplier.find_or_create_by(id:	1016	,name: "C4法事・こもりCo	",tax: 	1	)
Supplier.find_or_create_by(id:	1017	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1018	,name: "C4法事・花蓮	",tax: 	1	)
Supplier.find_or_create_by(id:	1019	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1020	,name: "C4法事・花月堂	",tax: 	1	)
Supplier.find_or_create_by(id:	1021	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1022	,name: "C4法事・ベリアール	",tax: 	7	)
Supplier.find_or_create_by(id:	1023	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1024	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	1025	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	2001	,name: "（アスク 21）	",tax: 	1	)
Supplier.find_or_create_by(id:	2002	,name: "（静岡園）03以前	",tax: 	1	)
Supplier.find_or_create_by(id:	2003	,name: "（味の匠）	",tax: 	1	)
Supplier.find_or_create_by(id:	2004	,name: "三興商事	",tax: 	1	)
Supplier.find_or_create_by(id:	2005	,name: "華仙	",tax: 	1	)
Supplier.find_or_create_by(id:	2006	,name: "豊神	",tax: 	1	)
Supplier.find_or_create_by(id:	2008	,name: "ワタウィル	",tax: 	1	)
Supplier.find_or_create_by(id:	2009	,name: "シャディショップ日新堂	",tax: 	1	)
Supplier.find_or_create_by(id:	2010	,name: "アカデミー総合	",tax: 	1	)
Supplier.find_or_create_by(id:	2011	,name: "㈱セレモア	",tax: 	7	)
Supplier.find_or_create_by(id:	2012	,name: "ケーオーエーコア	",tax: 	1	)
Supplier.find_or_create_by(id:	2013	,name: "",tax: 	1	)
Supplier.find_or_create_by(id:	99998	,name: "その他売上	",tax: 	1	)
Supplier.find_or_create_by(id:	99999	,name: "葬儀売上	",tax: 	1	)


Temple.find_or_create_by(id:1,name: "円照寺", address: "札幌市中央区北4条西28",tel: "0116315956")
Temple.find_or_create_by(id:2,name: "新善光寺", address: "札幌市中央区南6西1",tel: "0115110262")
Temple.find_or_create_by(id:3,name: "日正寺", address: "札幌市北区北36西4",tel: "0117168285")
Temple.find_or_create_by(id:10,name: "祖霊神社", address: "札幌市中央区南5西8",tel: "0115317306")
Temple.find_or_create_by(id:11,name: "世界救世教 新", address: "札幌市中央区北1東1",tel: "0112320461")
Temple.find_or_create_by(id:12,name: "北大寺", address: "札幌市北区北12西3",tel: "0117160264")
Temple.find_or_create_by(id:13,name: "浄圓寺", address: "札幌市中央区南19西16",tel: "0115221717")
Temple.find_or_create_by(id:14,name: "大法寺", address: "札幌市北区新琴似9-1",tel: "0117619411")
Temple.find_or_create_by(id:15,name: "眞願寺", address: "江別市7条8丁目",tel: "3823125")
Temple.find_or_create_by(id:16,name: "禅徳寺", address: "札幌市手稲区前田1条6丁目1-10",tel: "0116943611")
Temple.find_or_create_by(id:17,name: "玉宝禅寺", address: "札幌市清田区北野7条2丁目",tel: "0118837676")
Temple.find_or_create_by(id:18,name: "西本願寺札幌別院", address: "札幌市中央区北3条西19丁目",tel: "0116119322")
Temple.find_or_create_by(id:19,name: "大乗寺", address: "札幌市豊平区平岸１条８丁目",tel: "0118312500")
Temple.find_or_create_by(id:20,name: "新栄寺", address: "札幌市中央区南７条西３丁目",tel: "0115110927")
Temple.find_or_create_by(id:21,name: "乗善寺", address: "札幌市白石区本通２丁目南４",tel: "0118614382")
Temple.find_or_create_by(id:22,name: "禅宗寺", address: "札幌市東区東苗穂14条1丁目7-23",tel: "0117923322")
Temple.find_or_create_by(id:23,name: "浄圓寺", address: "札幌市中央区南19条西16丁目1-1",tel: "0115221717")
Temple.find_or_create_by(id:24,name: "地蔵寺", address: "札幌市中央区双子山1丁目10-12",tel: "0115614991")
Temple.find_or_create_by(id:25,name: "伊夜日子神社", address: "札幌市中央区南14条西4丁目",tel: "0115212565")


Collection.find_or_create_by(id:1	,text: "納入時担当者")
Collection.find_or_create_by(id:2	,text: "後日担当者")
Collection.find_or_create_by(id:3	,text: "後日代行")
Collection.find_or_create_by(id:4	,text: "振込")
Collection.find_or_create_by(id:9	,text: "その他")

Taxation.find_or_create_by(id:1,text: "外税四捨五入")
Taxation.find_or_create_by(id:2,text: "外税切り上げ")
Taxation.find_or_create_by(id:3,text: "外税切り捨て")
Taxation.find_or_create_by(id:4,text: "内税四捨五入")
Taxation.find_or_create_by(id:5,text: "内税切り上げ")
Taxation.find_or_create_by(id:6,text: "内税切り捨て")
Taxation.find_or_create_by(id:7,text: "非課税")



Item.find_or_create_by(supplier_id:	0	,item_id:	1	,name:"	祭壇使用料 札幌斎場	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	2	,name:"	祭壇使用料 むすめや斎場（	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	3	,name:"	祭壇使用料 北海斎場	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	4	,name:"	祭壇使用料 北広島斎場	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	5	,name:"	祭壇使用料 善光社（	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	6	,name:"	祭壇使用料 てんぱん（	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	7	,name:"	祭壇使用料 青柳	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	8	,name:"	祭壇使用料 はなみつ	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	9	,name:"	祭壇使用料 札幌御苑	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	10	,name:"	祭壇使用料 慶兆苑	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	11	,name:"	祭壇使用料 石狩やすらぎホール	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	12	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	13	,name:"	直下げ仮安置（会館など）	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	14	,name:"	新プランによる当社負担金	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	15	,name:"	ディアネス札幌 光熱費・設備費	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	99	,name:"	町内会館葬儀社負担金	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	100	,name:"	プロ役員入館料 (善光グループ）	", sell:	0	,cost:	1000.00	)
Item.find_or_create_by(supplier_id:	0	,item_id:	200	,name:"	東川下記念会館	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	1000	,name:"	会館使用料金など	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	0	,item_id:	99999	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	0	,name:"	斎場（札斎）役名あり	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1	,name:"	（棺 北斗）	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	2	,name:"	（棺 ノーマル）	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	3	,name:"	（棺 プレミアム）	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	4	,name:"	（棺 ルピア２面）	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	5	,name:"	（棺プレミアムＳＬ）	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	6	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	7	,name:"	ディアネス3×6	", sell:	0	,cost:	6500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	8	,name:"	ディアネス シール3付	", sell:	0	,cost:	8900.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	9	,name:"	ディアネス3×6(家紋付）	", sell:	0	,cost:	7500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	10	,name:"	ディアネス(家紋付）シール3付	", sell:	0	,cost:	9900.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	11	,name:"	通常看板3×9	", sell:	0	,cost:	8000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	12	,name:"	通常看板3×9 家紋付	", sell:	0	,cost:	9000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	13	,name:"	看板家紋入り	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	14	,name:"	アンドンシール	", sell:	0	,cost:	800	)
Item.find_or_create_by(supplier_id:	1	,item_id:	15	,name:"	屯田仕様看板	", sell:	0	,cost:	1800.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	16	,name:"	補助看板2×6	", sell:	0	,cost:	4000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	17	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	18	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	19	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	20	,name:"	寝具	", sell:	0	,cost:	1500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	21	,name:"	役員名簿 １０名まで	", sell:	0	,cost:	2000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	22	,name:"	役員名簿 ２０名まで	", sell:	0	,cost:	3000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	23	,name:"	役員名簿 ３０名まで	", sell:	0	,cost:	4000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	24	,name:"	モーニングセット	", sell:	0	,cost:	300	)
Item.find_or_create_by(supplier_id:	1	,item_id:	25	,name:"	式次第（1枚）	", sell:	0	,cost:	2000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	26	,name:"	役員名簿	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	29	,name:"	横断幕、垂れ幕の紙	", sell:	0	,cost:	2000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	30	,name:"	下足棚（中）	", sell:	0	,cost:	4500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	31	,name:"	シングルハンガーラック	", sell:	0	,cost:	2500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	32	,name:"	送料（往復）	", sell:	0	,cost:	4000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	33	,name:"	下足札	", sell:	0	,cost:	250	)
Item.find_or_create_by(supplier_id:	1	,item_id:	34	,name:"	前幕	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	35	,name:"	後幕	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	36	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	37	,name:"	会葬礼状	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	38	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	39	,name:"	位牌書シール	", sell:	0	,cost:	1000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	40	,name:"	位牌書き	", sell:	0	,cost:	3000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	41	,name:"	位牌７寸（学会用）	", sell:	0	,cost:	630	)
Item.find_or_create_by(supplier_id:	1	,item_id:	42	,name:"	位牌大中上10.0Ｈ40ｾﾝﾁ	", sell:	0	,cost:	1400.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	43	,name:"	ワンプ	", sell:	0	,cost:	160	)
Item.find_or_create_by(supplier_id:	1	,item_id:	44	,name:"	位牌袋白柄10.0用	", sell:	0	,cost:	280	)
Item.find_or_create_by(supplier_id:	1	,item_id:	45	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	46	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	47	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	48	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	49	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	50	,name:"	神式用品リース	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	51	,name:"	御玉代台 17-13	", sell:	0	,cost:	800	)
Item.find_or_create_by(supplier_id:	1	,item_id:	52	,name:"	大玉串台 17-18	", sell:	0	,cost:	800	)
Item.find_or_create_by(supplier_id:	1	,item_id:	53	,name:"	払い松立て	", sell:	0	,cost:	800	)
Item.find_or_create_by(supplier_id:	1	,item_id:	54	,name:"	雪洞	", sell:	0	,cost:	3000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	55	,name:"	五色旗	", sell:	0	,cost:	2500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	56	,name:"	八足	", sell:	0	,cost:	1200.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	57	,name:"	縄・御幣	", sell:	0	,cost:	1500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	58	,name:"	銘記	", sell:	0	,cost:	3000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	59	,name:"	春日灯	", sell:	0	,cost:	5000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	60	,name:"	軒縄（1間）	", sell:	0	,cost:	350	)
Item.find_or_create_by(supplier_id:	1	,item_id:	61	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	62	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	65	,name:"	五色旗セット	", sell:	0	,cost:	4500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	66	,name:"	八足(6尺)@3200	", sell:	0	,cost:	3200.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	67	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	68	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	69	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	70	,name:"	お厨子	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	71	,name:"	電動厨子	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	72	,name:"	電動厨子大型	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	73	,name:"	燭台・角香炉セット	", sell:	0	,cost:	2000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	74	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	75	,name:"	祭壇写真撮影	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	76	,name:"	集合写真撮影	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	77	,name:"	その他の写真	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	78	,name:"	手数料	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	79	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	80	,name:"	ポール 10本迄@1000	", sell:	0	,cost:	800	)
Item.find_or_create_by(supplier_id:	1	,item_id:	81	,name:"	垂木 1尺が@30	", sell:	0	,cost:	200	)
Item.find_or_create_by(supplier_id:	1	,item_id:	90	,name:"	大四華	", sell:	0	,cost:	2000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	99	,name:"	値引き	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	100	,name:"	その他	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	108	,name:"	ロイトンなど法要リース品	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	110	,name:"	キリストセット	", sell:	0	,cost:	8000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	112	,name:"	キリストローソク	", sell:	0	,cost:	1260.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	200	,name:"	葬儀施工手伝い通夜～出棺	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	201	,name:"	作業員1ｈ ＠2500	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1000	,name:"	祭壇設営（社葬）	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1001	,name:"	パイプイス＠400	", sell:	0	,cost:	8000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1002	,name:"	誘導灯＠1000（＠800）	", sell:	0	,cost:	8000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1003	,name:"	看板５－１１	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1004	,name:"	入口看板	", sell:	0	,cost:	7000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1005	,name:"	駐車場看板	", sell:	0	,cost:	4000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1006	,name:"	紙セット	", sell:	0	,cost:	8000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1007	,name:"	案内プレート＠2000	", sell:	0	,cost:	8000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1010	,name:"	12尺脚立	", sell:	0	,cost:	3000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1011	,name:"	下足棚中（50足）	", sell:	0	,cost:	4500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1015	,name:"	供花料名簿	", sell:	0	,cost:	3000.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1020	,name:"	リボンアクリルシール10枚	", sell:	0	,cost:	3500.00	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1022	,name:"	喪章 大旭光 黒	", sell:	0	,cost:	110	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1023	,name:"	喪章 大リボン 白バラ	", sell:	0	,cost:	390	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1024	,name:"	喪章 中リボン バラ紫	", sell:	0	,cost:	300	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1025	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1026	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1027	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1028	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1029	,name:"	印刷付き特大旭光 紫＠220	", sell:	0	,cost:	220	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1030	,name:"	印刷付き特大旭光＠200	", sell:	0	,cost:	200	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1031	,name:"	印刷付き大旭光＠110	", sell:	0	,cost:	110	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1032	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1033	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1034	,name:"	ｼｰﾙ特大旭光（黒）	", sell:	0	,cost:	550	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1035	,name:"	ｼｰﾙ特大旭光（紫）	", sell:	0	,cost:	570	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1036	,name:"	ｼｰﾙ大旭光（黒、紫）	", sell:	0	,cost:	450	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1037	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1038	,name:"	各種調整	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1039	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1040	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1041	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1042	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	1090	,name:"	搬入・撤去	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	2000	,name:"	法要／供物・菓子	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	5000	,name:"	社葬用品一式	", sell:	0	,cost:	0000000	)
Item.find_or_create_by(supplier_id:	1	,item_id:	90000	,name:"	当社什器備品	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	1	,item_id:	99999	,name:"	訂正	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	0	,name:"	その他	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	1	,name:"	香典返し(該当№がないもの)	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	2	,name:"	NK-510～512	", sell:	600	,cost:	225	)
Item.find_or_create_by(supplier_id:	2	,item_id:	3	,name:"	NK-514～516、521	", sell:	500	,cost:	225	)
Item.find_or_create_by(supplier_id:	2	,item_id:	4	,name:"	OK-50	", sell:	600	,cost:	225	)
Item.find_or_create_by(supplier_id:	2	,item_id:	5	,name:"	SEK-50	", sell:	600	,cost:	225	)
Item.find_or_create_by(supplier_id:	2	,item_id:	6	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	7	,name:"	NK-611	", sell:	700	,cost:	270	)
Item.find_or_create_by(supplier_id:	2	,item_id:	8	,name:"	BY-60	", sell:	700	,cost:	330	)
Item.find_or_create_by(supplier_id:	2	,item_id:	9	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	10	,name:"	NK-700番台	", sell:	800	,cost:	315	)
Item.find_or_create_by(supplier_id:	2	,item_id:	11	,name:"	OK-70	", sell:	800	,cost:	315	)
Item.find_or_create_by(supplier_id:	2	,item_id:	12	,name:"	RKD-701	", sell:	800	,cost:	315	)
Item.find_or_create_by(supplier_id:	2	,item_id:	13	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	14	,name:"	NK-800番台	", sell:	900	,cost:	360	)
Item.find_or_create_by(supplier_id:	2	,item_id:	15	,name:"	BY-80	", sell:	900	,cost:	440	)
Item.find_or_create_by(supplier_id:	2	,item_id:	16	,name:"	SEK-80	", sell:	900	,cost:	360	)
Item.find_or_create_by(supplier_id:	2	,item_id:	17	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	18	,name:"	NK-1000・1100番台	", sell:	1000.00	,cost:	450	)
Item.find_or_create_by(supplier_id:	2	,item_id:	19	,name:"	BY-100	", sell:	1000.00	,cost:	550	)
Item.find_or_create_by(supplier_id:	2	,item_id:	20	,name:"	SEK-100	", sell:	1000.00	,cost:	450	)
Item.find_or_create_by(supplier_id:	2	,item_id:	21	,name:"	OK-100	", sell:	1000.00	,cost:	450	)
Item.find_or_create_by(supplier_id:	2	,item_id:	22	,name:"	AK-10	", sell:	1000.00	,cost:	450	)
Item.find_or_create_by(supplier_id:	2	,item_id:	23	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	24	,name:"	NK-1200	", sell:	1200.00	,cost:	540	)
Item.find_or_create_by(supplier_id:	2	,item_id:	25	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	26	,name:"	NK-1500番台	", sell:	1500.00	,cost:	675	)
Item.find_or_create_by(supplier_id:	2	,item_id:	27	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	28	,name:"	NK-2100	", sell:	2000.00	,cost:	900	)
Item.find_or_create_by(supplier_id:	2	,item_id:	29	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	30	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	31	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	32	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	33	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	34	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	35	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	40	,name:"	送料/市内（600円）	", sell:	600	,cost:	425	)
Item.find_or_create_by(supplier_id:	2	,item_id:	41	,name:"	送料/道内（650円）	", sell:	650	,cost:	425	)
Item.find_or_create_by(supplier_id:	2	,item_id:	42	,name:"	送料/道外（1000円）	", sell:	1000.00	,cost:	900	)
Item.find_or_create_by(supplier_id:	2	,item_id:	43	,name:"	送料/離島・その他	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	44	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	50	,name:"	会葬礼状	", sell:	0	,cost:	80	)
Item.find_or_create_by(supplier_id:	2	,item_id:	51	,name:"	会葬礼状 2つ折り	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	52	,name:"	オリジナル会葬礼状	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	53	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	54	,name:"	版下代	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	55	,name:"	宛名書き	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	56	,name:"	挨拶状	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	57	,name:"	奉書礼状	", sell:	0	,cost:	70	)
Item.find_or_create_by(supplier_id:	2	,item_id:	58	,name:"	案内状	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	59	,name:"	喪中ハガキ	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	60	,name:"	その他 印刷物	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	61	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	62	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	63	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	64	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	65	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	70	,name:"	斎場持込料	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	71	,name:"	法要菓子・果物	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	72	,name:"	法要用品	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	73	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	74	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	75	,name:"		", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	100	,name:"	引出物（該当№がないもの）	", sell:	0	,cost:	0	)
Item.find_or_create_by(supplier_id:	2	,item_id:	101	,name:"	R-01 銘茶ギフト	", sell:	3000.00	,cost:	1440.00	)
Item.find_or_create_by(supplier_id:	2	,item_id:	102	,name:"	R-02 銘茶ギフト	", sell:	5000.00	,cost:	2400.00	)
Item.find_or_create_by(supplier_id:	2	,item_id:	103	,name:"	R-03 銘茶ギフト	", sell:	2000.00	,cost:	960	)
Item.find_or_create_by(supplier_id:	2	,item_id:	104	,name:"	R-04 銘茶ギフト	", sell:	2500.00	,cost:	1200.00	)
Item.find_or_create_by(supplier_id:	2	,item_id:	105	,name:"	R-05 銘茶ギフト	", sell:	1000.00	,cost:	480	)
Item.find_or_create_by(supplier_id:	2	,item_id:	106	,name:"	R-06 銘茶ギフト	", sell:	1500.00	,cost:	720	)
Item.find_or_create_by(supplier_id:	2	,item_id:	107	,name:"	R-07 ミル・茶セット	", sell:	5000.00	,cost:	2600.00	)
Item.find_or_create_by(supplier_id:	2	,item_id:	108	,name:"	R-08 梅・茶	", sell:	3000.00	,cost:	1800.00	)
Item.find_or_create_by(supplier_id:	2	,item_id:	109	,name:"	R-09 梅・茶	", sell:	2000.00	,cost:	1200.00	)
Item.find_or_create_by(supplier_id:	2	,item_id:	110	,name:"	R-10 梅・茶	", sell:	2500.00	,cost:	1500.00	)
Item.find_or_create_by(supplier_id:	2	,item_id:	111	,name:"	R-11 梅・茶	", sell:	5000.00	,cost:	3000.00	)




Faker::Config.locale = 'ja'
10.times do
    f = Faker::Name.first_name
    l = Faker::Name.last_name
    n = l+f
     m=Member.new(
        firstname: f,
        lastname: l,
        name: n,
        city: Faker::Address.street_name,
        mobile: Faker::PhoneNumber.cell_phone,
        tel: Faker::PhoneNumber.phone_number,
        streetaddress: Faker::Address.street_address,
        birthday:Faker::Date.forward(23).strftime('%Y-%m-%d'),
        gender: rand(1..2),
        sect: rand(1..21),
        kind: rand(1..9),
        postal: Faker::Address.postcode.truncate(7)
      )
     #p m
     m.save
end